controllers:
    resource:
        path: ../src/Infrastructure/Symfony/Controller/
        namespace: App\Infrastructure\Symfony\Controller
    type: attribute

api_login_check:
    path: /api/login_check